# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wisecow-main
  template:
    metadata:
      labels:
        app: wisecow-main
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: wisecow-main
        image: wisecow-main:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4499
        

---

# service
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4499
  selector:
    app: wisecow-main
